StartupEvents.registry('block', event => {
	event.create("unstable_element").material("honey").hardness(0).noCollision().defaultTranslucent().tag("minecraft:minable/hoe") // todo: .randomTick(ctx => {})
	event.create("toxic").material("clay").unbreakable()
	event.create("pure_math").lightLevel(1).material("snow").hardness(0).tag("minecraft:minable/hoe")
})
StartupEvents.registry('item', event => {
	event.create('3_rune')		.texture('kubejs:item/runes/3_rune')	.displayName("Rune o' :3")			.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('aaa_rune')	.texture('kubejs:item/runes/aaa_rune')	.displayName("Rune 'o §kUHACKER")		.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('crime_rune')	.texture('kubejs:item/runes/crime_rune')	.displayName("Rune o' Crime")			.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('cute_rune')	.texture('kubejs:item/runes/cute_rune')	.displayName("Rune o' Cuteness")		.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('hug_rune')	.texture('kubejs:item/runes/hug_rune')	.displayName("Rune o' Hugs")			.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('love_rune')	.texture('kubejs:item/runes/love_rune')	.displayName("Rune o' Love")			.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('lust_rune')	.texture('kubejs:item/runes/lust_rune')	.displayName("Rune o' Lust")			.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('magic_rune')	.texture('kubejs:item/runes/magic_rune')	.displayName("Rune o' Magic")			.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('math_rune')	.texture('kubejs:item/runes/math_rune')	.displayName("Rune o' Mathematics")		.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('meow_rune')	.texture('kubejs:item/runes/meow_rune')	.displayName("Rune o' MEOW")			.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('power_rune')	.texture('kubejs:item/runes/power_rune')	.displayName("Rune o' INFINITE POWER")	.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('pretty_rune')	.texture('kubejs:item/runes/pretty_rune')	.displayName("Rune o' Prettiness")		.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('gay_rune')	.texture('kubejs:item/runes/gay_rune')	.displayName("Rune o' Gay")			.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('silly_rune')	.texture('kubejs:item/runes/silly_rune')	.displayName("Rune o' Sillies")		.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('smart_rune')	.texture('kubejs:item/runes/smart_rune')	.displayName("Rune o' Smartness")		.tag("kubejs:rune").maxStackSize(8).fireResistant()
	event.create('sleepy_rune')	.texture('kubejs:item/runes/sleepy_rune')	.displayName("Rune o' Sleepy")		.tag("kubejs:rune").maxStackSize(8).fireResistant()
})