#!/usr/bin/env zsh
PATH="${PATH}:/usr/local/bin"

echo "=============================="
echo `date` "CURRENT TMUX SESSIONS:" `tmux ls`

if [[ -z `command -v tmux` ]]; then
    echo `date` "[ERROR] tmux not found on PATH"
    exit 1
elif [[ -z `tmux ls | grep craft` ]]; then
    echo `date` "[ERROR] tmux session 'craft' not found"
    exit 1
fi

session="craft"
window="${session}:0"
pane="${window}.0"

warning1='/say §dHi! The server will automatically restart for maintenance in §f5 minutes'
warning2="/say §dPlease wrap up anything critical. It is unlikely you need to restart your client."
restarting='/say §cRestarting'

echo `date` "[INFO] Attempting to send messages and a killcode to tmux session 'craft'"

/usr/local/bin/tmux send-keys -t "${pane}" "${warning1}"  Enter
sleep 2
/usr/local/bin/tmux send-keys -t "${pane}" "${warning2}" Enter
sleep 280
/usr/local/bin/tmux send-keys -t "${pane}" "${restarting}" Enter
echo `date` "[INFO] Restarting"
sleep 10
/usr/local/bin/tmux send-keys -t "${pane}" '/stop' Enter
